# Generated by Django 4.2.2 on 2023-06-17 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geolocation_fields.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0004_user_profile_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "author",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                (
                    "description",
                    models.TextField(
                        default="", max_length=255, verbose_name="description"
                    ),
                ),
                ("location", geolocation_fields.models.fields.PointField()),
                ("radius", models.FloatField()),
                ("created_date", models.DateTimeField(verbose_name="created_date")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="is_active"),
                ),
            ],
        ),
    ]
