# Generated by Django 4.2.2 on 2023-06-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_location_last_updated_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="last_updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
