# Generated by Django 4.2.2 on 2023-06-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_remove_location_person_location_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
