# Generated by Django 4.2.2 on 2023-06-17 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0003_team_team_members"),
        ("user", "0004_user_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="team_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="team.team",
            ),
        ),
    ]
