# Generated by Django 4.2.2 on 2023-06-17 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_remove_location_person_location_id"),
        ("user", "0005_user_team_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="team_id",
            new_name="team",
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.location",
            ),
        ),
    ]
