# Generated by Django 4.2.2 on 2023-06-16 23:31

from django.db import migrations, models
import django.db.models.deletion
import geolocation_fields.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_name", models.CharField(max_length=50)),
                ("job_description", models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_name", models.CharField(max_length=50)),
                ("status_description", models.TextField(max_length=200)),
                ("status_code", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TeamType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=50)),
                ("type_description", models.TextField(max_length=200)),
                ("min_member", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=50)),
                ("location", geolocation_fields.models.fields.PointField()),
                (
                    "team_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="team.status"
                    ),
                ),
                (
                    "team_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="team.teamtype"
                    ),
                ),
            ],
        ),
    ]
