# Generated by Django 4.2.2 on 2023-06-17 00:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("team", "0002_alter_team_team_status_alter_team_team_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="team_members",
            field=models.ManyToManyField(
                related_name="teams", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
